name: Send pending review notifications to reviewer on github-discussion
on:
  push:
    branches:
      - develop

jobs:
  send_notifications:
    name: Send pending review notifications
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: SD-13/pending-review-notifications@main
        with:
          category-name: 'Reviewer notifications'
          discussion-title: 'Pending Reviews'
          repo-token: ${{ secrets.DISCUSSION_NOTIFICATION_TOKEN }}
          review-turnaround-hours: 48
      - name: Report if failed
        if: ${{ failure() }}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "A pending-review-notification workflow failed."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
