name: Test own action on develop branch
on:
  push:
    branches:
      - develop

jobs:
  send_notifications:
    name: Send pending review notifications in test mode
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - name: Send notification(Test)
        run: |
          cd ${{ github.action_path }}
          python3 -m src_graphql.index --repo=${{ github.repository }} --token=${{ secrets.GITHUB_TOKEN }} --max-wait-hours=0 --verbose
        with:
          team-slug: test-team
          # GITHUB_TOKEN does not have right to send notifications, this is used
          # as a placeholder here as the action is running in test node.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          review-turnaround-hours: 0
        env:
          TEST_MODE_ENV: ${{ true }}
